#137005163 sort/filter search results
andela/anbu-rc pull request #10
Opened 2017-01-22 19:10 UTC by andela-aolaniran

#### What does this PR do?
Implements functionality for sorting and filtering of products search results
#### Description of Task to be completed?
After a search is completed, a user should be able to further refine through sorting and filtering.
#### How should this be manually tested?
Launch the app, visit the site, initiate a product search by typing a search query into the search input field, when results are displayed, controls which allow the user to further refine the search results though sorting and filtering are available at the top of the search results
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#137005163 Implement sorting and filtering of search results
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2017-01-23 08:23 UTC, victor-enogwe requested changes
fix inline comments and hound voilations

2017-01-23 08:28 UTC, andela-oaladeusi commented on imports/plugins/included/inventory/server/methods/statusChanges.js
> +        if (product) { // check that a product with the _id exists so we don't end up creating a new product with upsert
### Nit-Pick
I think it is better to write your comment before the "IF" condition

2017-01-23 09:10 UTC, andela-jare commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +  }
Why not use switch statements instead of multiple IF statements?

2017-01-23 09:11 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +        this.state.set("productSearchResults", filterSearchByVendor(filterBrand, sortProductSearchResults(sortOption, productResults)));
Fixed

2017-01-23 09:11 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +filterSearchByVendor = (vendor, productSearchResults) => {
Fixed

2017-01-23 09:11 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +function sortProductSearchResults(sortOption, productSearchResults) {
Fixed

2017-01-23 09:11 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +/**
Fixed

2017-01-23 09:12 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +/**
Fixed

2017-01-23 09:12 UTC, andela-aolaniran commented on imports/plugins/included/inventory/server/methods/statusChanges.js
> +        if (product) { // check that a product with the _id exists so we don't end up creating a new product with upsert
Noted.

2017-01-23 09:12 UTC, andela-aolaniran commented on imports/plugins/included/ui-search/client/templates/searchModal/searchModal.js
> +  }
Noted.

2017-01-23 16:08 UTC, victor-enogwe approved these changes

2017-01-27 15:36 UTC, andela-venogwe commented
looks good

2017-01-27 15:36 UTC, merged